### ISSUE TITLE
legalEntity property

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Business-Vocabulary#13]
If it is the design pattern "part of" I would use hasPart and its inverse isPartOf of dct. Only isPartOf is suggested in the description.

In addition, it is not very clear the objective of this property. Apart from the example of an organisation that includes some legalEntity (and btw a legalEntity can be seen as a general organisation) I do not see other examples for such a property. IMHO, It would be better to clarify this point.

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-04-23, a suggestion was made that this property should be reificated in order to be able to express information about the relationship between the Resource and the Legal Entity. This however seems better suited in an application profile as opposed to a Core Vocabulary.

**Comment by EmidioStani** [comment]
As agreed in the webinar of 09/11/2021 such property has been deleted
